### ISSUE TITLE
QUESTION about the model and code

### ISSUE THREAD

**Issue by xiaopanglee** [kaize0409/Meta-GDN_AnomalyDetection#2]
I can't get the performance of the SDN you showed in your paper using your code. Besides, I print the anomaly score of anomaly node and normal node, respectively, and I found that SGN can't assign the desired score to node , i.e. anomaly node don't get hight score , normal node don't get low score. what's the problems?

**Comment by BlueWhaleZhou** [comment]
Thank you for reaching out. The performance is largely dependent on the processed data. For your convenience, I attached the link of the meta data and the code for preprocessing, so that you can use them to explore the model. Thanks.

https://drive.google.com/drive/folders/1J2EaMqft15jqL8JwfTEnv3z4ezAxKX18?usp=sharing

**Comment by xiaopanglee** [comment]
I wanna confirm that the graph/Yelp.mat dataset  in your repo has been processed? shall I run the code you posted in this issue for Yelp.mat file again? cuz I found there are labeled anomaly nodes already after load your Yelp file. But I coundn't get desired results directely.

**Comment by BlueWhaleZhou** [comment]
Hi, I have done some updates to the code as well as the graph files. I think the code should work now. Please let me know if you have further questions. Thanks!
